[package]
name = "dao_indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros"] }
tendermint = "0.23.3"
tendermint-rpc = {version = "0.23.3", features = ["websocket-client"] }
futures = "0.3.21"
base64 = "0.13.0"
cosmrs = {version = "0.4.1", features = ["cosmwasm"] }
cosmwasm-std = "1.0.0-beta5"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0.79"
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
cw3-dao = { path = "../dao-contracts/contracts/cw3-dao" }
cw20-base = {  version = "0.11", features = ["library"] }
cw20 = "0.11.1"
cosmos-sdk-proto = "0.9.0"
