[package]
name = "dao_indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros"] }
tendermint = "0.23.3"
tendermint-rpc = {version = "0.23.3", features = ["websocket-client", "http-client"] }
futures = "0.3.21"
base64 = "0.13.0"
cosmrs = {version = "0.4.1", features = ["cosmwasm"] }
cosmwasm-std = "1.0.0-beta5"
bincode = "1.3.3"
bigdecimal = "0.1.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0.79"
dotenv = "0.15.0"
cw3-dao = { path = "../dao-contracts/contracts/cw3-dao" }
stake-cw20 = { path = "../dao-contracts/contracts/stake-cw20" }
cw20-base = {  version = "0.11", features = ["library"] }
cw20 = "0.11.1"
cosmos-sdk-proto = "0.9.0"
diesel = { version = "1.4.4", features = ["postgres", "numeric"] }
sha2 = "0.9.1"
prost = "0.9.0"
prost-types = "0.9"
