version: "3.9"

services:
  db:
    container_name: indexer_db
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  indexer:
    container_name: indexer_service
    # entrypoint: ["sh", "-c", "sleep 2073600"]
    build: .
    command: bash -c "cargo install diesel_cli --no-default-features --features "postgres" && diesel setup && diesel migration run && cargo run" 
    volumes:
      - .:/code
    network_mode: host 
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PERSISTENCE=true
      - ENABLE_INDEXER=true
      - TENDERMINT_INITIAL_BLOCK_HEIGHT=1055000
      - TENDERMINT_WEBSOCKET_URL=ws://54.177.5.188:26657/websocket
      - TENDERMINT_RPC_URL=http://54.177.5.188:26657
      - RUST_LOG="debug"
      - TENDERMINT_SAVE_ALL_BLOCKS=false
      - RUST_BACKTRACE=full
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
    depends_on:
      - db
